name: Build and Push Docker Image

on:
  workflow_dispatch:  
   inputs:
      path_to_binary:
        description: 'Path to binary'
        required: true
        type: string
      image_tag:
        description: 'Image Tag'
        required: true
        type: string
      image_repository:
        description: 'Image Repository'
        required: true
        type: string
      image_name:
        description: 'Image Name'
        required: true
        type: string

      #/environment:
      # description: 'Environment to run tests against'
      # type: environment
      # required: true 
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: dylanfeehan/${{inputs.image_name}}/:${{inputs.image_tag}}
          context: ${{inputs.path_to_binary}}
          push: true

